services:
  backend:
    build: ./codigo/planejador
    restart: always
    environment:
      MONGO_HOST: db
    ports:
      - 8080:8080
    networks:
      - react-spring
      - spring-mongo
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - 27017:27017
      - 9229:9229
    restart: always
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 3s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/data/db
    networks:
      - spring-mongo
  frontend:
    build:
      context: ./codigo/frontend
      target: development
    ports:
      - 3000:5173
    volumes:
      - ./frontend/src:/src
      - /project/node_modules
    networks:
      - react-spring
    depends_on:
      - backend
volumes:
  db-data: {}
networks:
  react-spring: {}
  spring-mongo: {}
